config/routes.rb
Rails.application.routes.draw do

  devise_for :songs

resources :songs, only: [:index, :show] do
	resources :lists
end
	authenticated :song do
		root 'songs#dashboard', as: "authenticated_root"
	end

		root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :song

  has_attached_file :mp3
  validates_attachment :mp3, :content_type => { :content_type => ["audio/mpeg", "audio/mp3"] },
  :file_name => { :matches => [/mp3\Z/] }
end

app/models/song.rb
class Song < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :title])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password_confirmation, :current_password,
  		:title, :description, :itunes, :amazon, :playstore])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :authenticate_song!, except: [:show]
	before_filter :require_permission
	before_action :find_song
	before_action :find_list, only: [:show, :edit, :update, :destroy]

	def new
		@list = @song.lists.new
	end

	def create
		@list = @song.lists.new  list_params
		if @list.save
			redirect_to song_list_path(@song, @list)
		else
			render 'new'
		end

	end
	
	def show
		@lists = List.where(song_id: @song).order("created_at DESC").reject{|e| e.id == @list.id}

	end

	def edit

	end

	def update
		if @list.update list_params
			redirect_to song_list_path(@song, @list), notice: "Song updated!"
		else 
			render 'edit'
		end
	end

	def destroy
		@list.destroy
		redirect_to root_path

		
	end
	private 

	def list_params
		params.require(:list).permit(:title, :description)
	end

	def find_song
		@song = Song.find(params[:song_id])

	end

	def find_list
		@list = List.find(params[:id])

	end

	def require_permission
		@song = Song.find(params[:song_id])
		if current_song != @song
			redirect_to root_path, notice: "Sorry, you don't have access to that page!"
		end

		
	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	before_action :find_song, only: [:show, :dashboard]
	before_action :find_list, only: [:show, :dashboard]

		def index
		@songs = Song.all.order("created_at DESC")
	end


	def show
		
	end
	
	def dashboard
	end

	private

	def find_song
		if params[:id].nil?
			@song = current_song
		else
		@song = Song.find(params[:id])
	end

	def find_list
		@lists = List.where(song_id: @song).order("created_at DESC")
	end

end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/_header.html.erb
 <header id="main_header" class="cf">
          <div class="wrapper_wide">
            <%= link_to "Spotflix", root_path, id: "logo" %>
            <nav>
              <ul>
                <% unless song_signed_in? %>
              <li><%= link_to "Explore", songs_path %></li>
              <li><%= link_to "Sign In", new_song_session_path%></li>
              <li><%= link_to "Create Artist", new_song_registration_path%></li>
              <% else %>
              <li><%= link_to "Dashboard", root_path %></li>
              <li><%= link_to "Explore", songs_path %></li>
              <li><%= link_to "Sign Out", destroy_song_session_path, method: :delete %> </li>
              <% end %>
              </ul>

            </nav>
          </div>
        </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotflix</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if notice %>
    <div id="notice_wrapper">
  	<p class="notice"><%= notice %></p>
    </div>
  	<% elsif alert %>
    <div id="notice_wrapper">
  	<p class="alert"><%= alert %></p>
  </div>
  	<% end %>

<% unless current_page?(root_path) %>
    <%= render 'layouts/header'; %>

        <% end %>


    <%= yield %>

    <script>
    $(document).ready(function() {
            setTimeout(function() {
        $('#notice_wrapper').fadeOut("slow", function() {
          $this.remove();

      });
    }, 4500 );

    });

    </script>
  </body>
</html>

app/views/lists/_form.html.erb
		<%= form_for ([@song, @list]) do |f| %>
			<div class="field">
				<%= f.label :title %><br>
				<%= f.text_field :title %>
			</div>

			<div class="field">
				<%= f.label :description %><br>
				<%= f.text_area :description %>
			</div>

	<%= f.submit class: "button button_highlight button_block" %>
		<% end %>

app/views/lists/edit.html.erb
<div id="song_show">
      <div id="show_banner">
        <div class="wrapper_skinny">
          <h1>Dashboard</h1>
          
        </div>
      </div>

      <div id="links">
        <div class="wrapper_skinny">
          <ul>
            <li><%= link_to "Albums", root_path %> </li>
            <li><%= link_to "New Album", new_song_list_path(@song) %></li>
            <li> <%= link_to "Account Settings", edit_song_registration_path %></li>
            <li><%= link_to "View Songs", song_path(current_song) %></li>
          </ul>
        </div>
      </div>
      <div id="form">
    <div class="wrapper_skinny">
		<%= render 'form' %>
	</div>
</div>

app/views/lists/new.html.erb
<div id="song_show">
      <div id="show_banner">
        <div class="wrapper_skinny">
          <h1>Dashboard</h1>
          
        </div>
      </div>

      <div id="links">
        <div class="wrapper_skinny">
          <ul>
            <li><%= link_to "Albums", root_path %> </li>
            <li><%= link_to "New Album", new_song_list_path(@song), class: "current" %></li>
            <li> <%= link_to "Account Settings", edit_song_registration_path %></li>
            <li><%= link_to "View Songs", song_path(current_song) %></li>
          </ul>
        </div>
      </div>
      <div id="form">
    <div class="wrapper_skinny">
		<%= render 'form' %>
	</div>
</div>

app/views/lists/show.html.erb
<div id="song_show">
		<div id="show_banner">
			<div class="wrapper_skinny">
				<h1><%= @song.title %></h1>
			<p class="description"><%= @song.description %></p>
			<% unless @song.itunes.blank? %>
				<a href="<%= @song.itunes %>" class="buy_link">iTunes</a>
			<% end %>
			<% unless @song.amazon.blank? %>
				<a href="<%= @song.amazon %>" class="buy_link">Amazon</a>
			<% end %>
			<% unless @song.playstore.blank? %>
				<a href="<%= @song.playstore %>" class="buy_link">Playstore</a>
			<% end %>
				
			</div>
		</div>
		<div id="breadcrumb">
			<%= link_to songs_path do %>
				All Songs
				<span>/</span>
				<%= link_to @song.title, song_path(@song) %>
				<span>/</span>
				<%= @list.title %>
				<% end %>

	<div id="album_content">
			<div class="wrapper_skinny">
				<!-- <img src="images/amy.jpg" alt="Songs I Wrote with Amy" class="current_album"> -->
			<h2><%= @list.title %></h2>
			<p class="description"><%= @list.description %>
							</p>
			</div>
		</div>
		</div>
		<div id="albums">
			<div class="wrapper_skinny">
				<ul class="cf">
					<% @lists.each do |list| %>
					<li class="cf">
						<div class="album_thumbnail">
							<a href="album.html">
								<!-- <img src="images/amy.jpg" alt="Songs I Wrote with Amy"> -->
							</a>
						</div>
						<div class="album_overview">
							<h2> 
					<%= link_to list.title, song_list_path(@song, list) %>
				</h2>
				<p class="description">
				<%= truncate(list.description, length: 170) %>
				</p>
			</div>
		</li>
		<% end %>	
				</ul>
			</div>
			<div class="pagination">
	<span class="previous_page disabled">Previous</span>
		<em class="current">1</em>
		<a href="#">2</a>
		<a class="next_page" href="#">Next</a>
		</div>
	</div>
</div>

app/views/songs/dashboard.html.erb
<%= render 'layouts/header'; %>

<div id="song_show">
      <div id="show_banner">
        <div class="wrapper_skinny">
          <h1>Dashboard</h1>
          
        </div>
      </div>

      <div id="links">
        <div class="wrapper_skinny">
          <ul>
            <li class="current">Album</li>
            <li><%= link_to "New Album", new_song_list_path(@song) %></li>
            <li> <%= link_to "Account Settings", edit_song_registration_path %></li>
            <li><%= link_to "View Songs", song_path(current_song) %></li>
          </ul>
        </div>
      </div>

            <div id="albums">
        <div class="wrapper_skinny">
          <ul class="cf">
            <% @lists.each do |list| %>
            <li class="cf">
              <div class="album_thumbnail">
                <a href="album.html">
                  <!-- <img src="images/amy.jpg" alt="Songs I Wrote with Amy"> -->
                </a>
              </div>
              <div class="album_overview">
                <h2> 
                  <%= link_to list.title, song_list_path(@song, list) %>
                </h2>
                <p class="description">
                <%= truncate(list.description, length: 170) %>
                </p>
                <div class="auth_link">
                 <%= link_to "Edit", edit_song_list_path(@song, list) %>
                  <%= link_to "Delete", song_list_path(@song, list), method: :delete, data:{confirm: "Are you sure you want to delete this?"} %>
                </div>
              </div>
            </li>
            <% end %>
            
            </li>
          </ul>
        </div>
        <div class="pagination">
    <span class="previous_page disabled">Previous</span>
      <em class="current">1</em>
      <a href="#">2</a>
      <a class="next_page" href="#">Next</a>
      </div>
    </div>

app/views/songs/index.html.erb
<div id="banner" class="songs_banner">
<h1>Discover your new favourite song or show</h1>
		</div>
			<div id="songs" class="cd">
			<div class="wrapper">
		<ul class="cf">
					<% @songs.each do |song| %>
					<%= link_to song do %>
	<li>
		<!-- <img src="images/edsheeran.jpg" alt="ed sheeran"> -->
			<div class="song_overview">
					<h2><%= song.title %></h2>
			<p class="song_count"></p>
							</div>
						</li>

			<% end %>

			<% end %>

		</ul>
	
	</div>
</div>
		

app/views/songs/show.html.erb
	<div id="song_show">
	<div id="show_banner">
	<div class="wrapper_skinny">
	<h1><%= @song.title %></h1>
	<p class="description"><%= @song.description %></p>
	<% unless @song.itunes.blank? %>
	<a href="<%= @song.itunes %>" class="buy_link">iTunes</a>
	<% end %>
	<% unless @song.amazon.blank? %>
	<a href="<%= @song.amazon %>" class="buy_link">Amazon</a>
	<% end %>
	<% unless @song.playstore.blank? %>
	<a href="<%= @song.playstore %>" class="buy_link">Playstore</a>
	<% end %>

	</div>
	</div>
	<div id="breadcrumb">
	<%= link_to songs_path do %>
	All Songs
	<span>/</span>
	<%= link_to @song.title, song_path(@song) %>
	<% end %>
	</div>
	<div id="albums">
	<div class="wrapper_skinny">
	<ul class="cf">
	<% @lists.each do |list| %>
		<li class="cf">
			<div class="album_thumbnail">
				<a href="#">
					<!-- <img src="images/amy.jpg" alt="Songs I Wrote with Amy"> -->
				</a>
			</div>
			<div class="album_overview">
				<h2> 
					<%= link_to list.title, song_list_path(@song, list) %>
				</h2>
				<p class="description">
				<%= truncate(list.description, length: 170) %>
				</p>
			</div>
		</li>
		<% end %>

		</li>
	</ul>
	</div>
	<div class="pagination">
	<span class="previous_page disabled">Previous</span>
	<em class="current">1</em>
	<a href="#">2</a>
	<a class="next_page" href="#">Next</a>
	</div>
	</div>
	</div>

app/views/welcome/index.html.erb
<div id="background">
			<header class="cf">
				<div class="wrapper_wide">
					<a href="#" id="logo">Spotflix</a>
					<nav>
						<ul>
							<li><%= link_to "Explore", songs_path %></li>
							<li><%= link_to "Sign In", new_song_session_path%></li>
							<li><%= link_to "Create Artist", new_song_registration_path%></li>
						</ul>

					</nav>
					</div>
			</header>
			<div class="wrapper_skinny">
				<h1>Discover new music<br>or add your own!</h1>
				<%= link_to "Create Artist", new_song_registration_path, class: "button button_highlight"%>

				<%= link_to "Explore", songs_path, class: "button button_white" %>
			</div>

		</div>